#!/bin/bash

# page scraper for text search

function usage
{
    echo "USAGE: $0 $1"
    exit
}

function dump
{
    URL=$1
    RELATIVE_URL=$(echo $URL | sed 's/.*.com//')
    echo "INSERT INTO tsearch(url, body) VALUES('$RELATIVE_URL', '$(lynx --dump --nolist --center=off $URL | sed "s/[\'\";,._-]/ /g" | xargs)');" >> insert_tsearch.sql
}

# main
if [[ $# -eq 0 ]]
then
    usage "url"
    exit
fi

# get url and dump into insert_tsearch.sql
dump $1

